spring:
  application:
    name: hibernate-demo
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/hibernate-demo
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
